services:
  db:
    image: postgres:12
    container_name: devblog_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: devblog
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: devblog
    volumes:
      - ./dbdata:/var/lib/postgresql/data